### ISSUE TITLE
The current context does not recognize the term 'AssetDatabase' error when compiling [FIX]

### ISSUE THREAD

**Issue by Cheesescodeiscool** [ducdat0507/JANOARG#6]
C:\Users\Ander\Music\JANOARG-master\Assets\Scripts\Behaviors\Files\JACEncoder.cs 

wrap the whole code (besides the imports) in this

#if UNITY_EDITOR
   [code stuff]
#endif

**Comment by BashhScriptKid** [comment]
You're not supposed to close this issue if no commits and prs are made for this yet, why???

**Comment by Cheesescodeiscool** [comment]
Its a note there is no reason to keep on opening it
